// utils/pdfGenerator.ts
import { jsPDF } from 'jspdf';
import { Flashcard } from '../types';
import { stripMarkdown } from './pptxGenerator';

export const createStyledPdf = (title: string, markdownContent: string): Blob => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  
  let y = 0;

  // Header Bar
  doc.setFillColor(79, 70, 229); // Indigo 600
  doc.rect(0, 0, pageWidth, 25, 'F');
  
  // Header Text
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(title, margin, 17);

  y = 40;
  
  // Content Parser
  const lines = markdownContent.split('\n');
  
  lines.forEach(line => {
    // Check for page break
    if (y > pageHeight - margin) { 
      doc.addPage(); 
      // Add simplified header on subsequent pages
      doc.setFillColor(79, 70, 229); 
      doc.rect(0, 0, pageWidth, 10, 'F');
      y = 25; 
    }

    if (line.trim() === '') {
      y += 5;
      return;
    }

    // Process different markdown elements
    if (line.startsWith('# ')) {
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      const text = stripMarkdown(line.replace('# ', ''));
      doc.text(text, margin, y);
      y += 12;
    } else if (line.startsWith('## ')) {
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(51, 65, 85);
      const text = stripMarkdown(line.replace('## ', ''));
      doc.text(text, margin, y);
      y += 10;
    } else if (line.startsWith('### ')) {
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(71, 85, 105);
      const text = stripMarkdown(line.replace('### ', ''));
      doc.text(text, margin, y);
      y += 8;
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(15, 23, 42);
      const bulletText = "• " + stripMarkdown(line.substring(2));
      const splitText = doc.splitTextToSize(bulletText, maxLineWidth - 5);
      doc.text(splitText, margin + 2, y);
      y += splitText.length * 6;
    } else {
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(15, 23, 42);
      const cleanText = stripMarkdown(line);
      const splitText = doc.splitTextToSize(cleanText, maxLineWidth);
      doc.text(splitText, margin, y);
      y += splitText.length * 6;
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by TrainerKit GenAI - Page ${i} of ${pageCount}`, 
      pageWidth / 2, 
      pageHeight - 10, 
      { align: 'center' }
    );
  }

  return doc.output('blob');
};

export const generateFlashcardsPdf = (flashcards: Flashcard[]): Blob => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Header Bar
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 25, 'F');
  
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("Study Flashcards", margin, 17);
  
  let y = 40;
  const cardHeight = 60;
  
  flashcards.forEach((card, index) => {
    if (y + cardHeight > pageHeight - margin) {
      doc.addPage();
      doc.setFillColor(79, 70, 229); 
      doc.rect(0, 0, pageWidth, 10, 'F');
      y = 25;
    }

    // Card Container
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.rect(margin, y, pageWidth - (margin * 2), cardHeight);
    
    // Card Front
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Card ${index + 1} - Front`, margin + 5, y + 10);
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    const frontLines = doc.splitTextToSize(
      stripMarkdown(card.front), 
      pageWidth - (margin * 2) - 10
    );
    doc.text(frontLines, margin + 5, y + 20);
    
    // Divider
    doc.setDrawColor(240, 240, 240);
    doc.line(margin + 5, y + 35, pageWidth - margin - 5, y + 35);

    // Card Back
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`Back`, margin + 5, y + 45);

    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    const backLines = doc.splitTextToSize(
      stripMarkdown(card.back), 
      pageWidth - (margin * 2) - 10
    );
    doc.text(backLines, margin + 5, y + 53);

    y += cardHeight + 10;
  });

  return doc.output('blob');
};